### ISSUE TITLE
Configure gt using custom host and port

### ISSUE THREAD

**Issue by a-b** [kantord/SeaGOAT#236]
I'm running seagoat-server in the cloud and want to configure `gt` to use an external host and port instead of `http://0.0.0.0:35257`. Please consider adding this feature.

**Comment by kantord** [comment]
I would definitely want to add this feature. Actually if you need it urgently, or you would like to contribute you, feel free to create a pull request. I can help you get it merged asap.

It's not so complicated to do this as this only affects the CLI.

I am explaining here how to implement it to make it easy for you. As a first step you can add a new flag/option to supply the remote server URL:

https://github.com/kantord/SeaGOAT/blob/4b6e74a06bf8ff02c0ca2a4e0c4df963d42636ea/seagoat/cli.py#L68-L107 

then, you just need to make sure that that argument is used instead of getting the server info here:

https://github.com/kantord/SeaGOAT/blob/4b6e74a06bf8ff02c0ca2a4e0c4df963d42636ea/seagoat/cli.py#L120-L121

A further improvement could be to create support for config files, and then in those config files there could be a configuration option to match a local folder with a remote server URL so that it always uses the remote server by default.

**Comment by kantord** [comment]
I am adding good first issue on this one as well, as a releasable implementation can be created without knowledge of the project structure using the information I shared above. Also testing should be easy, you can take inspiration in test_cli.py.

**Comment by kantord** [comment]
I would also like to note that it should be possible to create a feature that allows local users to import data from a remote server to avoid having to analyze the entire repository locally. Actually you should already be able to do this manually by simply copying the cache folder from the server to the local machine. **This would have the added benefit that the users are still able to search their local changes, and even when they are not connected to the internet. And it should also be faster by saving the network overhead**

Also I am working on creating a web-based GUI as well, using that your users will be able to search your repositories using SeaGOAT without installing anything on their computer: https://github.com/kantord/SeaGOAT-web

**Comment by kantord** [comment]
Now that configuration files are supported, this should be even more trivial to implement!
