### ISSUE TITLE
Ignore certain filetypes

### ISSUE THREAD

**Issue by vadi2** [kantord/SeaGOAT#244]
Seagoat is taking a very long while to scan [a repository](https://github.com/mudlet/mudlet) - and by the looks of it, it is stuck on the translation files which would add little value to the task at hand. Is there a way to ignore them?

Log: https://dpaste.com/4UK6GPF8D (started at 8:40, stopped it at 10:40 with little progress done)

**Comment by kantord** [comment]
I think that this would be a great feature indeed, it could be probably easy to add after this issue is fixed: https://github.com/kantord/SeaGOAT/issues/180

**Comment by kantord** [comment]
It got me thinking, are you sure that translation files would add little value?

I guess it depends on the use case, but I think it could actually be a great way to find things as the translation text could hold way more semantic information than the code itself. The downside that I can see is that you will find the translation file, not the code file. For me as a dev that would not be a dealbreaker, since once I have the translation key, it's trivial to find where it's used. And perhaps there could be an additional feature that actually finds the code related with translation keys as well

**Comment by kantord** [comment]
>  it is stuck on the translation files which would add little value to the task at hand. 

It depends on what you mean by stuck, SeaGOAT prioritizes files that have been changed recently, or that get changed often. In this case translation files are generated by an online platform? I guess maybe there could also be a feature that tries to detect if a folder is meant to store generated/downloaded code or it is code that is manually changed. Or perhaps this could be inferred based on the commit author

**Comment by michaelrhanson** [comment]
A related issue is that I would like SeaGOAT to ignore directories that contain intermediate products and final distributions, which are nearly always uninteresting... I thought that perhaps gitignore would be a good source for these but I agree that sometimes the gitignore files are still interesting for semantic search.  (Though ignoring the gitignore files would probably be a sensible default behavior which could be config'ed off)

**Comment by kantord** [comment]
Yeah, I think that it would be possible to either ignore these directories/files, that's pretty easy to implement. And it would also be easy to allow the user to configure these things.

But I am wondering if it's possible to come up with a relatively reliable heuristics to detect these scenarios.

**Comment by kantord** [comment]
Apart from ignoring, it's also possible to "penalize" such files, which would mean:

- They would appear generally lower on result pages, even if they are considered good results otherwise. They would still show up when they are very good results, and they could be on the top of the result page when no other good results are found
- They would be deprioritized for being analyzed, so the server would only start analyzing them once all other files have been analyzed

**Comment by kantord** [comment]
the original issue was fixed in https://github.com/kantord/SeaGOAT/pull/268

see documentation: https://kantord.github.io/SeaGOAT/latest/configuration/#server
