### ISSUE TITLE
Please, point what is the source of `qualityScore` in benchmarks

### ISSUE THREAD

**Issue by akhavr** [kantord/SeaGOAT#421]
I've explored all the code in `benchmark` folder and didn't found how `qualityScore` is generated.  Even if it is returned from openai, I don't see how it is incorporated in `example_data`, `full_example`, or final json file.  Nevertheless, benchmark example files do have such field and it 's used in ipython notebook.

Do I miss something obvious?

Thanks

**Comment by kantord** [comment]
It is generated by OpenAI indeed, take a look at the code that generates them: 

https://github.com/kantord/SeaGOAT/blob/232744e6006b871205020da0780becf40d183e70/benchmark/add_scores_to_examples.py#L34-L45

Admittedly this is not the best approach to measure the quality, but also manually making examples or manually scoring them does not seem ideal either, because there might be some bias introduced. So I am not sure what approach would both remove human bias but still guarantee that the queries are actually good quality. Telemetry could be an option if it was possible to know exactly what the correct answer is... but that is unfortunately not known, and even the user might not know it, which may be the reason they are searching for the code in the first place....

So if you have some better ideas for benchmarks, please let me know.

**Comment by akhavr** [comment]
Ah, yeah... Completely missed that script.

Thanks, if I will have better ideas for scoring the requests, I'll open a new issue.
